name: Build EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tkcalendar openpyxl

      - name: Build EXE using PyInstaller
        run: |
          pyinstaller --onefile --hidden-import=tkcalendar long_term_booking.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: long_term_booking-exe
          path: dist/long_term_booking.exe
